name: iconoir_flutter
description: Flutter library for Iconoir, the biggest open source icon library with tons of free icons.
version: 7.6.0
homepage: https://iconoir.com
repository: https://github.com/iconoir-icons/iconoir
funding:
  - https://opencollective.com/iconoir

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  fonts:
    - family: Iconoir Regular
      fonts:
        - asset: "fonts/iconoir_regular.ttf"
    - family: Iconoir Solid
      fonts:
        - asset: "fonts/iconoir_solid.ttf"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
